name:                text-format-heavy
version:             0.1.5.2
synopsis:            Full-weight string formatting library, analog of Python's string.format
description: >
                     This package contains full-featured string formatting function, similar to
                     Python's string.format. Features include:

                     * Automatically numbered variable placeholders;

                     * Positional variable placeholders;

                     * Named variable placeholders;

                     * Placeholders can be used in any order; one variable can be used several
                       times or not used at all.

                     * Specific format can be used for each variable substitution.

                     This package prefers functionality over "light weight" and (probably) performance. 
                     It also exposes all required interfaces to extend and customize it.

                     For more details, please refer to <https://github.com/portnov/text-format-heavy/wiki Wiki>.
                     See also the @examples/@ directory.

category:            Text
license:             BSD3
license-file:        LICENSE
author:              Ilya Portnov
maintainer:          portnov84@rambler.ru

extra-source-files:
  - ChangeLog.md
  - README.md
  - examples/test.hs
  - examples/Benchmarks.hs

library:
  source-dirs: .
  dependencies:
      - base >=4.8 && <5
      - text >=1.2 && <1.3
      - bytestring >= 0.10
      - parsec >=3.1 && <3.2
      - containers >= 0.5
      - data-default >= 0.7
      - time >= 1.5
      - template-haskell >= 2.8
      - th-lift
      - th-lift-instances
      - labels

tests:
  spec:
    source-dirs: tests
    main: Spec.hs
    dependencies:
      - base >= 4.8 && < 5
      - time >= 1.5
      - text-format-heavy
      - hspec

github: portnov/text-format-heavy
